# This Compose file is intended for local development, not production deployment.
#
# TODO change this file back to v.2 and set it up for local dev.
#

version: "3.2"

services:

  hugo:
    build: .
    ports:
     - "1001:80"

